@startuml
!include ../style.puml


participant ":TagCommandParser" as TagCommandParser LOGIC_COLOR
participant ":UpdatePersonTagsDescriptor" as UpdatePersonTagsDescriptor LOGIC_COLOR
participant ":TagCommand" as TagCommand LOGIC_COLOR

[-> TagCommandParser : parse("1 at/tall \ndt/short at/handsome")
ref over TagCommandParser: parse command arguments
|||
create UpdatePersonTagsDescriptor
TagCommandParser -> UpdatePersonTagsDescriptor
activate UpdatePersonTagsDescriptor
return descriptor
|||
ref over TagCommandParser: verify has tag to update
|||
create TagCommand
    TagCommandParser -> TagCommand: new TagCommand(1, descriptor)
    activate TagCommand
    return command
    [<--TagCommandParser : command

@enduml
