@startuml
!include ../style.puml


participant ":TagCommandParser" as TagCommandParser LOGIC_COLOR
participant ":UpdatePersonTagsDescriptor" as UpdatePersonTagsDescriptor LOGIC_COLOR
participant ":TagCommand" as TagCommand LOGIC_COLOR

[-> TagCommandParser : parse("1 at/tall \ndt/short at/handsome")

|||

TagCommandParser -> TagCommandParser: parseArguments("1 at/tall dt/short at/handsome")

|||

create UpdatePersonTagsDescriptor
TagCommandParser -> UpdatePersonTagsDescriptor: UpdatePersonTagsDescriptor(tagsToAdd, tagsToDelete)
activate UpdatePersonTagsDescriptor
return descriptor

|||

TagCommandParser -> TagCommandParser: verifyHasTagToUpdate(descriptor)

|||
create TagCommand
    TagCommandParser -> TagCommand: TagCommand(index, descriptor)
    activate TagCommand
    return command
    [<--TagCommandParser : command

@enduml
