@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR
skinparam classBackgroundColor LOGIC_COLOR

Class TagCommand
Class Index
Class UpdatePersonTagsDescriptor
Class Tag

TagCommand --> "1" Index
TagCommand --> "1" UpdatePersonTagsDescriptor
UpdatePersonTagsDescriptor --> "~* tags to add" Tag
UpdatePersonTagsDescriptor --> "~* tags to delete" Tag

@enduml
