@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":TagCommandParser" as TagCommandParser LOGIC_COLOR
participant "t:TagCommand" as TagCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR

[-> LogicManager : execute("tag 1 at/tall \ndt/short at/handsome")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("tag 1 at/tall \ndt/short at/handsome")
activate AddressBookParser

create TagCommandParser
AddressBookParser -> TagCommandParser
activate TagCommandParser

TagCommandParser --> AddressBookParser
deactivate TagCommandParser

AddressBookParser -> TagCommandParser : parse("1 at/tall \ndt/short at/handsome")
activate TagCommandParser

create TagCommand
TagCommandParser -> TagCommand
activate TagCommand

TagCommand --> TagCommandParser : t
deactivate TagCommand

TagCommandParser --> AddressBookParser : t
deactivate TagCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
TagCommandParser -[hidden]-> AddressBookParser
destroy TagCommandParser

AddressBookParser --> LogicManager : t
deactivate AddressBookParser

LogicManager -> TagCommand : execute()
activate TagCommand


create CommandResult
TagCommand -> CommandResult
activate CommandResult

CommandResult --> TagCommand : result
deactivate CommandResult

TagCommand --> LogicManager : result
deactivate TagCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
TagCommand -[hidden]-> LogicManager
destroy TagCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
