'@startuml
!include ../style.puml

participant ":PriorityCommandParser" as PriorityCommandParser LOGIC_COLOR
participant ":PriorityCommand" as PriorityCommand LOGIC_COLOR

[-> PriorityCommandParser : parse("1 high")

ref over PriorityCommandParser
parse index and arguments
end

opt valid index and arguments
    create PriorityCommand
    PriorityCommandParser -> PriorityCommand : PriorityCommand(1, p)
    activate PriorityCommand
    note left
    A Priority object, p, is created
    from the parsing action above
    if the index and arguments are valid
    end note
    return command
    PriorityCommandParser -->[ : command
end

@enduml


