@startuml
skin rose
skinparam ActivityFontSize 13
skinparam ArrowFontSize 12

start
:User provides the priority to assign to a person;

if () then
    :Update priority of the target person ;
    if () then
    :Save updated person to model;
    else ([updated person's priority is unchanged])
        stop
    endif
    stop
else ([provided priority is invalid])
    stop
endif
@enduml
