@startuml
skin rose
skinparam ActivityFontSize 13
skinparam ArrowFontSize 12

start
:User provides the priority level to assign to a person;

if () then
    :Update priority level of the target person ;
    if () then
    :Save updated person to model;
    else ([updated person's priority level is unchanged])
        stop
    endif
    stop
else ([provided priority level is invalid])
    stop
endif
@enduml
